### ISSUE TITLE
lab is undefined in [gx,gy,idx] = grid_communities(lab); % BCT function

### ISSUE THREAD

**Issue by ChenSD** [brain-networks/edge-centric_demo#2]
Hello,
  I was trying to run the demo and found that lab is undefined in [gx,gy,idx] = grid_communities(lab); % BCT function.

Regards,
Shengdong

**Comment by faskowit** [comment]
Hi Shengdong, 

I assume you figured out that the grid_communities function is from the [Brain Connectivity Toolbox](https://sites.google.com/site/bctnet/)? Otherwise, the _lab_ variable should be loaded when you load `example_data.mat`

Cheers, 
Josh
